// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/Experience.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Networking.Experience {

  /// <summary>Holder for reflection information generated from Proto/Experience.proto</summary>
  public static partial class ExperienceReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/Experience.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExperienceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZQcm90by9FeHBlcmllbmNlLnByb3RvEhVuZXR3b3JraW5nLmV4cGVyaWVu",
            "Y2UaE1Byb3RvL0FkZHJlc3MucHJvdG8aE1Byb3RvL1JlcXVlc3QucHJvdG8a",
            "EFByb3RvL1BhZ2UucHJvdG8iKgoPUHJvdG9idWZNZXNzYWdlEhcKD21lc3Nh",
            "Z2VPck9iamVjdBgBIAEoCSI0ChRQcm90b2J1ZlN0b2NrUmVxdWVzdBIKCgJp",
            "ZBgBIAEoBRIQCghxdWFudGl0eRgCIAEoBSLqAQoRRXhwZXJpZW5jZU1lc3Nh",
            "Z2USCgoCaWQYASABKAUSDwoHcGljdHVyZRgCIAEoCRIMCgRuYW1lGAMgASgJ",
            "Eg0KBXByaWNlGAQgASgBEg0KBXN0b2NrGAUgASgFEhMKC2Rlc2NyaXB0aW9u",
            "GAYgASgJEhoKEmV4cGVyaWVuY2VWYWxpZGl0eRgHIAEoBRISCgpjYXRlZ29y",
            "eUlkGAggASgFEhIKCnByb3ZpZGVySWQYCSABKAUSMwoHYWRkcmVzcxgKIAEo",
            "CzIiLm5ldHdvcmtpbmcuYWRkcmVzcy5BZGRyZXNzTWVzc2FnZSKGAQoVRXhw",
            "ZXJpZW5jZUxpc3RNZXNzYWdlEj0KC2V4cGVyaWVuY2VzGAEgAygLMigubmV0",
            "d29ya2luZy5leHBlcmllbmNlLkV4cGVyaWVuY2VNZXNzYWdlEi4KCHBhZ2VJ",
            "bmZvGAIgASgLMhwubmV0d29ya2luZy5wYWdlLlBhZ2VNZXNzYWdlMt0JChFF",
            "eHBlcmllbmNlU2VydmljZRJtChlnZXRBbGxQcm92aWRlckV4cGVyaWVuY2Vz",
            "EiIubmV0d29ya2luZy5yZXF1ZXN0LlJlcXVlc3RNZXNzYWdlGiwubmV0d29y",
            "a2luZy5leHBlcmllbmNlLkV4cGVyaWVuY2VMaXN0TWVzc2FnZRJwChhnZXRB",
            "bGxXZWJTaG9wRXhwZXJpZW5jZXMSJi5uZXR3b3JraW5nLnJlcXVlc3QuUGFn",
            "ZVJlcXVlc3RNZXNzYWdlGiwubmV0d29ya2luZy5leHBlcmllbmNlLkV4cGVy",
            "aWVuY2VMaXN0TWVzc2FnZRJjCg1hZGRFeHBlcmllbmNlEigubmV0d29ya2lu",
            "Zy5leHBlcmllbmNlLkV4cGVyaWVuY2VNZXNzYWdlGigubmV0d29ya2luZy5l",
            "eHBlcmllbmNlLkV4cGVyaWVuY2VNZXNzYWdlEmEKEWdldEV4cGVyaWVuY2VC",
            "eUlkEiIubmV0d29ya2luZy5yZXF1ZXN0LlJlcXVlc3RNZXNzYWdlGigubmV0",
            "d29ya2luZy5leHBlcmllbmNlLkV4cGVyaWVuY2VNZXNzYWdlElMKCWlzSW5T",
            "dG9jaxIiLm5ldHdvcmtpbmcucmVxdWVzdC5SZXF1ZXN0TWVzc2FnZRoiLm5l",
            "dHdvcmtpbmcucmVxdWVzdC5SZXF1ZXN0TWVzc2FnZRJaChBkZWxldGVFeHBl",
            "cmllbmNlEiIubmV0d29ya2luZy5yZXF1ZXN0LlJlcXVlc3RNZXNzYWdlGiIu",
            "bmV0d29ya2luZy5yZXF1ZXN0LlJlcXVlc3RNZXNzYWdlElUKC3JlbW92ZVN0",
            "b2NrEiIubmV0d29ya2luZy5yZXF1ZXN0LlJlcXVlc3RNZXNzYWdlGiIubmV0",
            "d29ya2luZy5yZXF1ZXN0LlJlcXVlc3RNZXNzYWdlEnMKH2dldEFsbFByb3Zp",
            "ZGVyRXhwZXJpZW5jZXNCeU5hbWUSIi5uZXR3b3JraW5nLnJlcXVlc3QuUmVx",
            "dWVzdE1lc3NhZ2UaLC5uZXR3b3JraW5nLmV4cGVyaWVuY2UuRXhwZXJpZW5j",
            "ZUxpc3RNZXNzYWdlEmsKF2dldEV4cGVyaWVuY2VCeUNhdGVnb3J5EiIubmV0",
            "d29ya2luZy5yZXF1ZXN0LlJlcXVlc3RNZXNzYWdlGiwubmV0d29ya2luZy5l",
            "eHBlcmllbmNlLkV4cGVyaWVuY2VMaXN0TWVzc2FnZRJlChFnZXRUb3BFeHBl",
            "cmllbmNlcxIiLm5ldHdvcmtpbmcucmVxdWVzdC5SZXF1ZXN0TWVzc2FnZRos",
            "Lm5ldHdvcmtpbmcuZXhwZXJpZW5jZS5FeHBlcmllbmNlTGlzdE1lc3NhZ2US",
            "aAoUZ2V0U29ydGVkRXhwZXJpZW5jZXMSIi5uZXR3b3JraW5nLnJlcXVlc3Qu",
            "UmVxdWVzdE1lc3NhZ2UaLC5uZXR3b3JraW5nLmV4cGVyaWVuY2UuRXhwZXJp",
            "ZW5jZUxpc3RNZXNzYWdlEmQKDmVkaXRFeHBlcmllbmNlEigubmV0d29ya2lu",
            "Zy5leHBlcmllbmNlLkV4cGVyaWVuY2VNZXNzYWdlGigubmV0d29ya2luZy5l",
            "eHBlcmllbmNlLkV4cGVyaWVuY2VNZXNzYWdlQgJQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Networking.Address.AddressReflection.Descriptor, global::Networking.Request.RequestReflection.Descriptor, global::Networking.Page.PageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Networking.Experience.ProtobufMessage), global::Networking.Experience.ProtobufMessage.Parser, new[]{ "MessageOrObject" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Networking.Experience.ProtobufStockRequest), global::Networking.Experience.ProtobufStockRequest.Parser, new[]{ "Id", "Quantity" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Networking.Experience.ExperienceMessage), global::Networking.Experience.ExperienceMessage.Parser, new[]{ "Id", "Picture", "Name", "Price", "Stock", "Description", "ExperienceValidity", "CategoryId", "ProviderId", "Address" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Networking.Experience.ExperienceListMessage), global::Networking.Experience.ExperienceListMessage.Parser, new[]{ "Experiences", "PageInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtobufMessage : pb::IMessage<ProtobufMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufMessage> _parser = new pb::MessageParser<ProtobufMessage>(() => new ProtobufMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Networking.Experience.ExperienceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMessage(ProtobufMessage other) : this() {
      messageOrObject_ = other.messageOrObject_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMessage Clone() {
      return new ProtobufMessage(this);
    }

    /// <summary>Field number for the "messageOrObject" field.</summary>
    public const int MessageOrObjectFieldNumber = 1;
    private string messageOrObject_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageOrObject {
      get { return messageOrObject_; }
      set {
        messageOrObject_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageOrObject != other.MessageOrObject) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageOrObject.Length != 0) hash ^= MessageOrObject.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageOrObject.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MessageOrObject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageOrObject.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MessageOrObject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageOrObject.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageOrObject);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufMessage other) {
      if (other == null) {
        return;
      }
      if (other.MessageOrObject.Length != 0) {
        MessageOrObject = other.MessageOrObject;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MessageOrObject = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MessageOrObject = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufStockRequest : pb::IMessage<ProtobufStockRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufStockRequest> _parser = new pb::MessageParser<ProtobufStockRequest>(() => new ProtobufStockRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufStockRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Networking.Experience.ExperienceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufStockRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufStockRequest(ProtobufStockRequest other) : this() {
      id_ = other.id_;
      quantity_ = other.quantity_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufStockRequest Clone() {
      return new ProtobufStockRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 2;
    private int quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufStockRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufStockRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Quantity != other.Quantity) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Quantity != 0) hash ^= Quantity.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Quantity != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Quantity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Quantity != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Quantity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Quantity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quantity);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufStockRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Quantity != 0) {
        Quantity = other.Quantity;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Quantity = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Quantity = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExperienceMessage : pb::IMessage<ExperienceMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExperienceMessage> _parser = new pb::MessageParser<ExperienceMessage>(() => new ExperienceMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExperienceMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Networking.Experience.ExperienceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExperienceMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExperienceMessage(ExperienceMessage other) : this() {
      id_ = other.id_;
      picture_ = other.picture_;
      name_ = other.name_;
      price_ = other.price_;
      stock_ = other.stock_;
      description_ = other.description_;
      experienceValidity_ = other.experienceValidity_;
      categoryId_ = other.categoryId_;
      providerId_ = other.providerId_;
      address_ = other.address_ != null ? other.address_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExperienceMessage Clone() {
      return new ExperienceMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "picture" field.</summary>
    public const int PictureFieldNumber = 2;
    private string picture_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Picture {
      get { return picture_; }
      set {
        picture_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 4;
    private double price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "stock" field.</summary>
    public const int StockFieldNumber = 5;
    private int stock_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Stock {
      get { return stock_; }
      set {
        stock_ = value;
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 6;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "experienceValidity" field.</summary>
    public const int ExperienceValidityFieldNumber = 7;
    private int experienceValidity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ExperienceValidity {
      get { return experienceValidity_; }
      set {
        experienceValidity_ = value;
      }
    }

    /// <summary>Field number for the "categoryId" field.</summary>
    public const int CategoryIdFieldNumber = 8;
    private int categoryId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CategoryId {
      get { return categoryId_; }
      set {
        categoryId_ = value;
      }
    }

    /// <summary>Field number for the "providerId" field.</summary>
    public const int ProviderIdFieldNumber = 9;
    private int providerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ProviderId {
      get { return providerId_; }
      set {
        providerId_ = value;
      }
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 10;
    private global::Networking.Address.AddressMessage address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Networking.Address.AddressMessage Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExperienceMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExperienceMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Picture != other.Picture) return false;
      if (Name != other.Name) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Price, other.Price)) return false;
      if (Stock != other.Stock) return false;
      if (Description != other.Description) return false;
      if (ExperienceValidity != other.ExperienceValidity) return false;
      if (CategoryId != other.CategoryId) return false;
      if (ProviderId != other.ProviderId) return false;
      if (!object.Equals(Address, other.Address)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Picture.Length != 0) hash ^= Picture.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Price != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Price);
      if (Stock != 0) hash ^= Stock.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (ExperienceValidity != 0) hash ^= ExperienceValidity.GetHashCode();
      if (CategoryId != 0) hash ^= CategoryId.GetHashCode();
      if (ProviderId != 0) hash ^= ProviderId.GetHashCode();
      if (address_ != null) hash ^= Address.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Picture.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Picture);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Price != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Price);
      }
      if (Stock != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Stock);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Description);
      }
      if (ExperienceValidity != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ExperienceValidity);
      }
      if (CategoryId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(CategoryId);
      }
      if (ProviderId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(ProviderId);
      }
      if (address_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Address);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Picture.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Picture);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Price != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Price);
      }
      if (Stock != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Stock);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Description);
      }
      if (ExperienceValidity != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ExperienceValidity);
      }
      if (CategoryId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(CategoryId);
      }
      if (ProviderId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(ProviderId);
      }
      if (address_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Address);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Picture.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Picture);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Price != 0D) {
        size += 1 + 8;
      }
      if (Stock != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Stock);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (ExperienceValidity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExperienceValidity);
      }
      if (CategoryId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CategoryId);
      }
      if (ProviderId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProviderId);
      }
      if (address_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExperienceMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Picture.Length != 0) {
        Picture = other.Picture;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Price != 0D) {
        Price = other.Price;
      }
      if (other.Stock != 0) {
        Stock = other.Stock;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.ExperienceValidity != 0) {
        ExperienceValidity = other.ExperienceValidity;
      }
      if (other.CategoryId != 0) {
        CategoryId = other.CategoryId;
      }
      if (other.ProviderId != 0) {
        ProviderId = other.ProviderId;
      }
      if (other.address_ != null) {
        if (address_ == null) {
          Address = new global::Networking.Address.AddressMessage();
        }
        Address.MergeFrom(other.Address);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Picture = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 33: {
            Price = input.ReadDouble();
            break;
          }
          case 40: {
            Stock = input.ReadInt32();
            break;
          }
          case 50: {
            Description = input.ReadString();
            break;
          }
          case 56: {
            ExperienceValidity = input.ReadInt32();
            break;
          }
          case 64: {
            CategoryId = input.ReadInt32();
            break;
          }
          case 72: {
            ProviderId = input.ReadInt32();
            break;
          }
          case 82: {
            if (address_ == null) {
              Address = new global::Networking.Address.AddressMessage();
            }
            input.ReadMessage(Address);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Picture = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 33: {
            Price = input.ReadDouble();
            break;
          }
          case 40: {
            Stock = input.ReadInt32();
            break;
          }
          case 50: {
            Description = input.ReadString();
            break;
          }
          case 56: {
            ExperienceValidity = input.ReadInt32();
            break;
          }
          case 64: {
            CategoryId = input.ReadInt32();
            break;
          }
          case 72: {
            ProviderId = input.ReadInt32();
            break;
          }
          case 82: {
            if (address_ == null) {
              Address = new global::Networking.Address.AddressMessage();
            }
            input.ReadMessage(Address);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExperienceListMessage : pb::IMessage<ExperienceListMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExperienceListMessage> _parser = new pb::MessageParser<ExperienceListMessage>(() => new ExperienceListMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExperienceListMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Networking.Experience.ExperienceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExperienceListMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExperienceListMessage(ExperienceListMessage other) : this() {
      experiences_ = other.experiences_.Clone();
      pageInfo_ = other.pageInfo_ != null ? other.pageInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExperienceListMessage Clone() {
      return new ExperienceListMessage(this);
    }

    /// <summary>Field number for the "experiences" field.</summary>
    public const int ExperiencesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Networking.Experience.ExperienceMessage> _repeated_experiences_codec
        = pb::FieldCodec.ForMessage(10, global::Networking.Experience.ExperienceMessage.Parser);
    private readonly pbc::RepeatedField<global::Networking.Experience.ExperienceMessage> experiences_ = new pbc::RepeatedField<global::Networking.Experience.ExperienceMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Networking.Experience.ExperienceMessage> Experiences {
      get { return experiences_; }
    }

    /// <summary>Field number for the "pageInfo" field.</summary>
    public const int PageInfoFieldNumber = 2;
    private global::Networking.Page.PageMessage pageInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Networking.Page.PageMessage PageInfo {
      get { return pageInfo_; }
      set {
        pageInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExperienceListMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExperienceListMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!experiences_.Equals(other.experiences_)) return false;
      if (!object.Equals(PageInfo, other.PageInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= experiences_.GetHashCode();
      if (pageInfo_ != null) hash ^= PageInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      experiences_.WriteTo(output, _repeated_experiences_codec);
      if (pageInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PageInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      experiences_.WriteTo(ref output, _repeated_experiences_codec);
      if (pageInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PageInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += experiences_.CalculateSize(_repeated_experiences_codec);
      if (pageInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PageInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExperienceListMessage other) {
      if (other == null) {
        return;
      }
      experiences_.Add(other.experiences_);
      if (other.pageInfo_ != null) {
        if (pageInfo_ == null) {
          PageInfo = new global::Networking.Page.PageMessage();
        }
        PageInfo.MergeFrom(other.PageInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            experiences_.AddEntriesFrom(input, _repeated_experiences_codec);
            break;
          }
          case 18: {
            if (pageInfo_ == null) {
              PageInfo = new global::Networking.Page.PageMessage();
            }
            input.ReadMessage(PageInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            experiences_.AddEntriesFrom(ref input, _repeated_experiences_codec);
            break;
          }
          case 18: {
            if (pageInfo_ == null) {
              PageInfo = new global::Networking.Page.PageMessage();
            }
            input.ReadMessage(PageInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
