// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/ProviderNetworking.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Com.Example.Dataserver.Networking {
  public static partial class ProtobufProviderService
  {
    static readonly string __ServiceName = "com.example.dataserver.networking.ProtobufProviderService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Com.Example.Dataserver.Networking.ProtobufProvider> __Marshaller_com_example_dataserver_networking_ProtobufProvider = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Com.Example.Dataserver.Networking.ProtobufProvider.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Com.Example.Dataserver.Networking.ProtobufResponse> __Marshaller_com_example_dataserver_networking_ProtobufResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Com.Example.Dataserver.Networking.ProtobufResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Com.Example.Dataserver.Networking.ProtobufRequest> __Marshaller_com_example_dataserver_networking_ProtobufRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Com.Example.Dataserver.Networking.ProtobufRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Com.Example.Dataserver.Networking.ProtobufProviderList> __Marshaller_com_example_dataserver_networking_ProtobufProviderList = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Com.Example.Dataserver.Networking.ProtobufProviderList.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufProvider, global::Com.Example.Dataserver.Networking.ProtobufResponse> __Method_createProvider = new grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufProvider, global::Com.Example.Dataserver.Networking.ProtobufResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "createProvider",
        __Marshaller_com_example_dataserver_networking_ProtobufProvider,
        __Marshaller_com_example_dataserver_networking_ProtobufResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufRequest, global::Com.Example.Dataserver.Networking.ProtobufProviderList> __Method_getAllProviders = new grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufRequest, global::Com.Example.Dataserver.Networking.ProtobufProviderList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getAllProviders",
        __Marshaller_com_example_dataserver_networking_ProtobufRequest,
        __Marshaller_com_example_dataserver_networking_ProtobufProviderList);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Com.Example.Dataserver.Networking.ProviderNetworkingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for ProtobufProviderService</summary>
    public partial class ProtobufProviderServiceClient : grpc::ClientBase<ProtobufProviderServiceClient>
    {
      /// <summary>Creates a new client for ProtobufProviderService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProtobufProviderServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ProtobufProviderService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProtobufProviderServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProtobufProviderServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProtobufProviderServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufResponse createProvider(global::Com.Example.Dataserver.Networking.ProtobufProvider request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return createProvider(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufResponse createProvider(global::Com.Example.Dataserver.Networking.ProtobufProvider request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_createProvider, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufResponse> createProviderAsync(global::Com.Example.Dataserver.Networking.ProtobufProvider request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return createProviderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufResponse> createProviderAsync(global::Com.Example.Dataserver.Networking.ProtobufProvider request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_createProvider, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufProviderList getAllProviders(global::Com.Example.Dataserver.Networking.ProtobufRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getAllProviders(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufProviderList getAllProviders(global::Com.Example.Dataserver.Networking.ProtobufRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getAllProviders, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufProviderList> getAllProvidersAsync(global::Com.Example.Dataserver.Networking.ProtobufRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getAllProvidersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufProviderList> getAllProvidersAsync(global::Com.Example.Dataserver.Networking.ProtobufRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getAllProviders, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ProtobufProviderServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProtobufProviderServiceClient(configuration);
      }
    }

  }
}
#endregion
