// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/ProviderNetworking.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Example.Dataserver.Networking {

  /// <summary>Holder for reflection information generated from Proto/ProviderNetworking.proto</summary>
  public static partial class ProviderNetworkingReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/ProviderNetworking.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProviderNetworkingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5Qcm90by9Qcm92aWRlck5ldHdvcmtpbmcucHJvdG8SIWNvbS5leGFtcGxl",
            "LmRhdGFzZXJ2ZXIubmV0d29ya2luZyIqCg9Qcm90b2J1Zk1lc3NhZ2USFwoP",
            "bWFzc2FnZU9yT2JqZWN0GAEgASgJMvsEChdQcm90b2J1ZlByb3ZpZGVyU2Vy",
            "dmljZRJ4Cg5jcmVhdGVQcm92aWRlchIyLmNvbS5leGFtcGxlLmRhdGFzZXJ2",
            "ZXIubmV0d29ya2luZy5Qcm90b2J1Zk1lc3NhZ2UaMi5jb20uZXhhbXBsZS5k",
            "YXRhc2VydmVyLm5ldHdvcmtpbmcuUHJvdG9idWZNZXNzYWdlEnkKD2dldEFs",
            "bFByb3ZpZGVycxIyLmNvbS5leGFtcGxlLmRhdGFzZXJ2ZXIubmV0d29ya2lu",
            "Zy5Qcm90b2J1Zk1lc3NhZ2UaMi5jb20uZXhhbXBsZS5kYXRhc2VydmVyLm5l",
            "dHdvcmtpbmcuUHJvdG9idWZNZXNzYWdlEnkKD2dldFByb3ZpZGVyQnlJZBIy",
            "LmNvbS5leGFtcGxlLmRhdGFzZXJ2ZXIubmV0d29ya2luZy5Qcm90b2J1Zk1l",
            "c3NhZ2UaMi5jb20uZXhhbXBsZS5kYXRhc2VydmVyLm5ldHdvcmtpbmcuUHJv",
            "dG9idWZNZXNzYWdlEnYKDGVkaXRQcm92aWRlchIyLmNvbS5leGFtcGxlLmRh",
            "dGFzZXJ2ZXIubmV0d29ya2luZy5Qcm90b2J1Zk1lc3NhZ2UaMi5jb20uZXhh",
            "bXBsZS5kYXRhc2VydmVyLm5ldHdvcmtpbmcuUHJvdG9idWZNZXNzYWdlEngK",
            "DnJlbW92ZVByb3ZpZGVyEjIuY29tLmV4YW1wbGUuZGF0YXNlcnZlci5uZXR3",
            "b3JraW5nLlByb3RvYnVmTWVzc2FnZRoyLmNvbS5leGFtcGxlLmRhdGFzZXJ2",
            "ZXIubmV0d29ya2luZy5Qcm90b2J1Zk1lc3NhZ2VCAlABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Example.Dataserver.Networking.ProtobufMessage), global::Com.Example.Dataserver.Networking.ProtobufMessage.Parser, new[]{ "MassageOrObject" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtobufMessage : pb::IMessage<ProtobufMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufMessage> _parser = new pb::MessageParser<ProtobufMessage>(() => new ProtobufMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Example.Dataserver.Networking.ProviderNetworkingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMessage(ProtobufMessage other) : this() {
      massageOrObject_ = other.massageOrObject_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMessage Clone() {
      return new ProtobufMessage(this);
    }

    /// <summary>Field number for the "massageOrObject" field.</summary>
    public const int MassageOrObjectFieldNumber = 1;
    private string massageOrObject_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MassageOrObject {
      get { return massageOrObject_; }
      set {
        massageOrObject_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MassageOrObject != other.MassageOrObject) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MassageOrObject.Length != 0) hash ^= MassageOrObject.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MassageOrObject.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MassageOrObject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MassageOrObject.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MassageOrObject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MassageOrObject.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MassageOrObject);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufMessage other) {
      if (other == null) {
        return;
      }
      if (other.MassageOrObject.Length != 0) {
        MassageOrObject = other.MassageOrObject;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MassageOrObject = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MassageOrObject = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
