// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/ProviderNetworking.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Com.Example.Dataserver.Networking {
  public static partial class ProtobufProviderService
  {
    static readonly string __ServiceName = "com.example.dataserver.networking.ProtobufProviderService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Com.Example.Dataserver.Networking.ProtobufMessage> __Marshaller_com_example_dataserver_networking_ProtobufMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Com.Example.Dataserver.Networking.ProtobufMessage.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufMessage, global::Com.Example.Dataserver.Networking.ProtobufMessage> __Method_createProvider = new grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufMessage, global::Com.Example.Dataserver.Networking.ProtobufMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "createProvider",
        __Marshaller_com_example_dataserver_networking_ProtobufMessage,
        __Marshaller_com_example_dataserver_networking_ProtobufMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufMessage, global::Com.Example.Dataserver.Networking.ProtobufMessage> __Method_getAllProviders = new grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufMessage, global::Com.Example.Dataserver.Networking.ProtobufMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getAllProviders",
        __Marshaller_com_example_dataserver_networking_ProtobufMessage,
        __Marshaller_com_example_dataserver_networking_ProtobufMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufMessage, global::Com.Example.Dataserver.Networking.ProtobufMessage> __Method_getProviderById = new grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufMessage, global::Com.Example.Dataserver.Networking.ProtobufMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getProviderById",
        __Marshaller_com_example_dataserver_networking_ProtobufMessage,
        __Marshaller_com_example_dataserver_networking_ProtobufMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufMessage, global::Com.Example.Dataserver.Networking.ProtobufMessage> __Method_editProvider = new grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufMessage, global::Com.Example.Dataserver.Networking.ProtobufMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "editProvider",
        __Marshaller_com_example_dataserver_networking_ProtobufMessage,
        __Marshaller_com_example_dataserver_networking_ProtobufMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufMessage, global::Com.Example.Dataserver.Networking.ProtobufMessage> __Method_removeProvider = new grpc::Method<global::Com.Example.Dataserver.Networking.ProtobufMessage, global::Com.Example.Dataserver.Networking.ProtobufMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "removeProvider",
        __Marshaller_com_example_dataserver_networking_ProtobufMessage,
        __Marshaller_com_example_dataserver_networking_ProtobufMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Com.Example.Dataserver.Networking.ProviderNetworkingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for ProtobufProviderService</summary>
    public partial class ProtobufProviderServiceClient : grpc::ClientBase<ProtobufProviderServiceClient>
    {
      /// <summary>Creates a new client for ProtobufProviderService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProtobufProviderServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ProtobufProviderService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProtobufProviderServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProtobufProviderServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProtobufProviderServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufMessage createProvider(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return createProvider(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufMessage createProvider(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_createProvider, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufMessage> createProviderAsync(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return createProviderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufMessage> createProviderAsync(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_createProvider, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufMessage getAllProviders(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getAllProviders(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufMessage getAllProviders(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getAllProviders, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufMessage> getAllProvidersAsync(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getAllProvidersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufMessage> getAllProvidersAsync(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getAllProviders, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufMessage getProviderById(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getProviderById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufMessage getProviderById(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getProviderById, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufMessage> getProviderByIdAsync(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getProviderByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufMessage> getProviderByIdAsync(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getProviderById, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufMessage editProvider(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return editProvider(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufMessage editProvider(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_editProvider, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufMessage> editProviderAsync(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return editProviderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufMessage> editProviderAsync(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_editProvider, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufMessage removeProvider(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return removeProvider(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Com.Example.Dataserver.Networking.ProtobufMessage removeProvider(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_removeProvider, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufMessage> removeProviderAsync(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return removeProviderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Dataserver.Networking.ProtobufMessage> removeProviderAsync(global::Com.Example.Dataserver.Networking.ProtobufMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_removeProvider, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ProtobufProviderServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProtobufProviderServiceClient(configuration);
      }
    }

  }
}
#endregion
